=== Harena09/Bookstore/Booklist.dtd
<!ELEMENT BookList (Book*)>
    
<!ELEMENT Book (Title, Author+, ISBN, PublicationYear, Genre+, Price, Image, Description, BestSeller?)>
    
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT PublicationYear (YEAR,DATE*)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Image (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT BestSeller (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ENTITY % currency "(USD)">
<!ATTLIST BookList
    xmlns CDATA #FIXED 'http://www.example.com/booklist'
    xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'>

=== Harena09/Bookstore/programpage.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BookList SYSTEM "BookList.dtd" [
    <!-- Internal DTD subset for entity declaration -->
    <!ENTITY publisherInfo "For more information, visit the author's website.">
]>
<?xml-stylesheet type="text/xsl" href="design.xsl"?>
<BookList xmlns="http://www.example.com/booklist" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <Book>
        <Title>Introduction to Algorithms</Title> <!-- The title of the book -->
        <Author>Thomas H. Cormen et al.</Author> <!-- The author(s) of the book -->
        <ISBN>978-0262033848</ISBN> <!-- ISBN number of the book -->
        <PublicationYear>
		   <Year>2009</Year>
		   <Date>10/06 </Date>
		</PublicationYear>
        <Genre>Education</Genre>
		<BestSeller>false</BestSeller> <!-- Indicates if the book is a bestseller -->
        <Price>$450.25</Price> <!-- Price of the book -->
        <Image>https://m.media-amazon.com/images/I/61Pgdn8Ys-L._AC_UF1000,1000_QL80_.jpg</Image>
       <Description>Introduction to Algorithms uniquely combines rigor and comprehensiveness. It covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers, with self-contained chapters and algorithms in pseudocode. &publisherInfo; </Description> 
    </Book>

    <!-- Additional <Book> elements would follow the same pattern -->
    <Book>
        <Title>365 Days</Title>
        <Author>Blanka Lipinska</Author>
        <ISBN>978-0262033848</ISBN>
        <PublicationYear>
		   	<Year>2018</Year>
		    <Date>04/07</Date>
		</PublicationYear>
        <Genre>Literature</Genre>
		<BestSeller>true</BestSeller>
        <Price>$10.00</Price>         <Image>https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982174309/365-days-9781982174309_hr.jpg</Image>
      <Description>The first book in the trilogy, 365 Days, is a story of Laura's captivity, where she struggles to come to terms with her situation and her growing feelings for Massimo. The novel is full of explicit sex scenes, violence, and intrigue that will keep readers hooked until the end.</Description>  

    </Book>

    <Book>
        <Title>Atomic Habits</Title>
        <Author>James Clear</Author>
        <ISBN>978-0262033848</ISBN>
        <PublicationYear>
		   <Year>2018</Year>
		   <Date>16/10</Date>
		</PublicationYear>
        <Genre>Education</Genre>
		<BestSeller>false</BestSeller>
        <Price>$30.25</Price>
        <Image>https://m.media-amazon.com/images/I/81YkqyaFVEL._AC_UF1000,1000_QL80_.jpg</Image>
        <Description>Atomic Habits by James Clear is a comprehensive, practical guide on how to change your habits and get 1% better every day. Using a framework called the Four Laws of Behavior Change, Atomic Habits teaches readers a simple set of rules for creating good habits and breaking bad ones.</Description>

    </Book>

    <Book>
        <Title>Pride and Prejudice</Title>
        <Author>Jane Austen</Author>
        <ISBN>978-0140430721</ISBN>
        <PublicationYear>
		   <Year>28/01</Year>
		   <Date>1813</Date>
		</PublicationYear>
        <Genre>Romance</Genre>
		<BestSeller>false</BestSeller>
        <Price>$30.25</Price>
        <Image>https://images.penguinrandomhouse.com/cover/9780593622452</Image>
       <Description>Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry.</Description>
    </Book>

    <Book>
        <Title>When Breath Becomes Air</Title>
        <Author>Paul Kalanithi</Author>
        <ISBN>978-0812988406</ISBN>
        <PublicationYear>
		   <Year>12/01</Year>
		   <Date>2016</Date>
		</PublicationYear>
        <Genre>Non-fiction</Genre>
		<BestSeller>true</BestSeller>
        <Price>$30.60</Price>
        
        <Image>https://m.media-amazon.com/images/I/91iZ2ZQduBL._AC_UF894,1000_QL80_.jpg</Image>
        <Description>When Breath Becomes Air by Paul Kalanithi is a memoir that follows a neurosurgeon's journey upon receiving a terminal cancer diagnosis. It offers a touching and insightful reflection on life, death, and the importance of finding meaning in one's limited time.</Description>

    </Book>

    <Book>
        <Title>Twilight(Book Set)</Title>
        <Author>Stephenie Meyer</Author>
        <ISBN>978-1415634844</ISBN>
        <PublicationYear>
		   <Year>2005-2020</Year>
		   <Date></Date>
		</PublicationYear>
        <Genre>Romance, Young Adult</Genre>
		<BestSeller>false</BestSeller>
        <Price>$300.60</Price>
       
        <Image>https://m.media-amazon.com/images/I/61dj8UY9g1L._AC_UF1000,1000_QL80_.jpg</Image>
        <Description>Twilight, by Stephenie Meyer, is a young adult adventure-romance about a teenage girl who falls in love with a vampire. Her struggle to build a relationship in a world filled with suspicion and danger helped make the book a number-one New York Times bestseller.</Description>
    </Book>    

    <Book>
        <Title>Palestine</Title>
        <Author>Joe Sacco </Author>
        <ISBN>978-1415634844</ISBN>
        <PublicationYear>
		   <Year>1993</Year>
		   <Date></Date>
		</PublicationYear>
        <Genre>Non-fiction</Genre>
		<BestSeller>false</BestSeller>
        <Price>$350.60</Price>
       
        <Image>https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1569917057i/769712.jpg</Image>
        <Description>Palestine is a non-fiction graphic novel written and drawn by Joe Sacco about his experiences in the West Bank and the Gaza Strip in December 1991 and January 1992. Sacco's portrayal of the situation emphasizes the history and plight of the Palestinian people, as a group and as individuals.</Description>
    </Book>    
 
    <Book>
        <Title>White Noise</Title>
        <Author>Don Dellilo</Author>
        <ISBN>786-1415634800</ISBN>
        <PublicationYear>
		   <Year>1985</Year>
		   <Date>21/01</Date>
		</PublicationYear>
        <Genre>Literature</Genre>
		<BestSeller>false</BestSeller>
        <Price>$456.60</Price>
       
        <Image>https://ik.imagekit.io/panmac/tr:f-auto,di-placeholder_portrait_aMjPtD9YZ.jpg,w-171/edition/9781529077261.jpg</Image>
        <Description>White Noise is the eighth novel by Don DeLillo, published by Viking Press in 1985. It won the U.S. National Book Award for Fiction. White Noise is a cornerstone example of postmodern literature. It is widely considered DeLillo's breakout work and brought him to the attention of a much larger audience.</Description>
    </Book>    
    
    <Book>
        <Title>This is Going to Hurt</Title>
        <Author>Adam Kay</Author>
        <ISBN>9781529062335</ISBN>
        <PublicationYear>
		   <Year>2022</Year>
		   <Date>03/02</Date>
		</PublicationYear>
        <Genre>Humor</Genre>
		<BestSeller>false</BestSeller>
        <Price>$458.60</Price>
       
        <Image>https://ik.imagekit.io/panmac/tr:f-auto,di-placeholder_portrait_aMjPtD9YZ.jpg,w-270/edition/9781529062335.jpg</Image>
        <Description>This is Going to Hurt: Secret Diaries of a Junior Doctor is a nonfiction book by the British comedy writer Adam Kay, published in 2017 by Picador. It is a collection of diary entries written by Kay during his medical training from 2004 to 2010.</Description>
    </Book>    

     <Book>
        <Title>If only I had told her</Title>
        <Author>Laura Nowlin</Author>
        <ISBN>9781529062335</ISBN>
        <PublicationYear>
		   <Year>2024</Year>
		   <Date>06/02</Date>
		</PublicationYear>
        <Genre>Young adult</Genre>
		<BestSeller>false</BestSeller>
        <Price>$230.60</Price>
       
        <Image>https://m.media-amazon.com/images/I/81uMF1t16LL._SY466_.jpg</Image>
        <Description>An intensely emotional and gripping companion novel to Laura Nowlin's USA Today and New York Times Bestselling novel If He Had Been With Me about the love that both breaks and heals us.</Description>
    </Book>    

     <Book>
        <Title>If He Had Been with Me</Title>
        <Author>Laura Nowlin</Author>
        <ISBN>9781529062335</ISBN>
        <PublicationYear>
		   <Year>2019</Year>
		   <Date>06/11</Date>
		</PublicationYear>
        <Genre>Young adult</Genre>
		<BestSeller>false</BestSeller>
        <Price>$235.60</Price>
       
        <Image>https://m.media-amazon.com/images/I/61tdwW3Nm8L._SY466_.jpg</Image>
        <Description>A heartrending tale of missed chances and what might have been If he had been with me, everything would be different. For one thing, Finn wouldn't have been in that car, on that road, on that night.</Description>
    </Book>   
    
     <Book>
        <Title>Empire of the Vampire</Title>
        <Author>Jay Kristoff</Author>
        <ISBN>978-0262033848</ISBN>
        <PublicationYear>
		  <Year>2009</Year>
		   <Date>06/11</Date>
		</PublicationYear>
        <Genre>Literature</Genre>
		<BestSeller>true</BestSeller>
        <Price>$45.25</Price>
        <Image>https://m.media-amazon.com/images/I/81TTmyqWoWL._AC_UF1000,1000_QL80_.jpg</Image>
       <Description>Imprisoned by the very monsters he vowed to destroy, the last silversaint is forced to tell his story. A story of legendary battles and forbidden love, of faith lost and friendships won, of the Wars of the Blood and the Forever King and the quest for humanityâ€™s last remaining hope:

The Holy Grail.
</Description> 
    </Book>

    <Book>
        <Title>Empire of the Damned</Title>
        <Author>Jay Kristoff</Author>
        <ISBN>978-0262033848</ISBN>
        <PublicationYear>
		   <Year>2024</Year>
		   <Date>10/02</Date>
		</PublicationYear>
        <Genre>Literature</Genre>
